<a href="https://colab.research.google.com/github/ShubhGupta2004/mlLearning/blob/main/Copy_of_data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

import library

In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [22]:
dataset = pd.read_csv('Data.csv')
#independet varieble
x=dataset.iloc[: , :-1].values
#dependet var or var to find the value
y=dataset.iloc[: ,-1].values

In [23]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [24]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [26]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan,strategy='mean')
imp.fit(x[: , 1:3])
#update the value into new matrix
x[: , 1:3]=imp.transform(x[: , 1:3])

In [27]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [36]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#transformation of data
cut = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[0])], remainder = 'passthrough')
x=np.array(cut.fit_transform(x))


In [37]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [38]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y= le.fit_transform(y)

In [39]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [46]:
from scipy.sparse.construct import random
from sklearn.model_selection import train_test_split

#splitting the data set
xTrain,xTest,yTrain,yTest = train_test_split(x,y,test_size=0.2,random_state=1)


In [47]:
print(xTrain)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [52]:
print(yTrain)

[0 1 0 0 1 1 0 1]


In [53]:
print(xTest)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [54]:
print(yTest)

[0 1]


## Feature Scaling

In [56]:
#some features not to be dominated by other features in data set
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
xTrain[: , 3:] = sc.fit_transform(xTrain[: , 3:])
xTest[: ,3: ] = sc.transform(xTest[: ,3:])


In [57]:
print(xTrain)

[[1.0 0.0 0.0 1.2909944487358058 -0.1915918438457856 -1.0781259408412427]
 [1.0 0.0 1.0 -0.7745966692414835 -0.014117293757057902
  -0.07013167641635401]
 [0.0 1.0 0.0 -0.7745966692414835 0.5667085065333239 0.6335624327104546]
 [1.0 0.0 0.0 1.2909944487358058 -0.3045301939022488 -0.30786617274297895]
 [1.0 0.0 0.0 1.2909944487358058 -1.901801144700799 -1.4204636155515822]
 [0.0 1.0 0.0 -0.7745966692414835 1.1475343068237056 1.2326533634535488]
 [1.0 0.0 1.0 -0.7745966692414835 1.4379472069688966 1.5749910381638883]
 [0.0 1.0 0.0 -0.7745966692414835 -0.7401495441200352 -0.5646194287757336]]


In [58]:
print(xTest)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
